name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.8  
      - name: Build & Test project
        run: mvn -B clean package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: azure/docker-login@v1
        name: Login to Docker repository
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push Docker image to GitHub
        run: |
          docker build . -t docker.pkg.github.com/wearearima/petclinic-docker-ci-cd-aws/petclinic:latest
          docker push docker.pkg.github.com/wearearima/petclinic-docker-ci-cd-aws/petclinic:latest          
      - name: Run Docker container in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login docker.pkg.github.com -u wearearima --password-stdin && sudo docker stop petclinic && sudo docker rm -f petclinic && sudo docker rmi docker.pkg.github.com/wearearima/petclinic-docker-ci-cd-aws/petclinic && sudo docker run --name petclinic -d -p 8081:8080 docker.pkg.github.com/wearearima/petclinic-docker-ci-cd-aws/petclinic:latest
          
          
